name: Bazel CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Mount Bazel cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazel-repo
        key: ${{ runner.os }}-bazel-${{ hashFiles('MODULE.bazel', 'WORKSPACE', '.bazelrc', '.bazelversion') }}
        restore-keys: |
          ${{ runner.os }}-bazel-
    
    - name: Install Bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64"
        chmod +x bazelisk-linux-amd64
        sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
    
    - name: Build all targets
      run: |
        bazel build //...
    
    - name: Run all tests
      run: |
        bazel test //... --test_output=errors
    
    - name: Verify formatting
      run: |
        # Add formatting checks if needed
        # For example: bazel run //:buildifier.check
    
    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: |
          bazel-testlogs/
        retention-days: 7

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true

    - name: Install Buildifier
      run: |
        # Use our setup script instead of installing via Go
        chmod +x ./setup_buildifier.sh
        ./setup_buildifier.sh
        echo "$(pwd)/bin" >> $GITHUB_PATH
    
    - name: Lint Bazel files
      run: |
        chmod +x ./buildifier.check.sh
        ./buildifier.check.sh
    
    - name: Setup Python linting environment
      run: |
        chmod +x ./setup_lint_venv.sh
        ./setup_lint_venv.sh
    
    - name: Lint Python files
      run: |
        ./python_lint.sh
    
    - name: Setup Kotlin linting environment
      run: |
        chmod +x ./setup_ktlint.sh
        ./setup_ktlint.sh
    
    - name: Lint Kotlin files
      run: |
        chmod +x ./ktlint_check.sh
        ./ktlint_check.sh
